"use client";
import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { useState } from "react";
import { TotalUsageContext } from "./(context)/TotalUsageContext";
import { UserSubscriptionContext } from "./(context)/UserSubscriptionContext";
import { UpdateCreditUsageContext } from "./(context)/UpdateCreditUsageContext";
import Header from "@/components/Header";
import SideNav from "@/components/SideNav";

const inter = Outfit({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [totalUsage, setTotalUsage] = useState<Number>(0);
  const [userSubscription, setUserSubscription] = useState<Boolean>(false);
  const [updateCreditUsage, setUpdateCreditUsage] = useState<Date>();

  return (
    <TotalUsageContext.Provider value={{ totalUsage, setTotalUsage }}>
      <UserSubscriptionContext.Provider
        value={{ userSubscription, setUserSubscription }}
      >
        <UpdateCreditUsageContext.Provider
          value={{ updateCreditUsage, setUpdateCreditUsage }}
        >
          <ClerkProvider>
            <html lang="en">
              <body className={inter.className}>
                <div className="bg-slate-200 h-screen">
                  <div className="md:w-64 hidden md:block fixed">
                    <SideNav />
                  </div>
                  <div className="md:ml-64">
                    <Header />
                {children}
                </div>
                </div>
              </body>
            </html>
          </ClerkProvider>
        </UpdateCreditUsageContext.Provider>
      </UserSubscriptionContext.Provider>
    </TotalUsageContext.Provider>
  );
}
